#for all genes with doubles
zan<-read.table("withdoubles_tot.txt", header=T)
str(zan)
zan$bias_ch <- factor(zan$bias_ch, levels=c("A_male","X_male", "A_female","X_female", "A_unbiased", "X_unbiased"))
new <- subset(zan, age=="new")
old <- subset(zan, age=="old")
fem <- subset(zan, bias=="female")
mal <- subset(zan, bias=="male")
un <- subset(zan, bias=="unbiased")
newfem <- subset(new, bias=="female")
newmal <- subset(new, bias=="male")
newun <- subset(new, bias=="unbiased")

png("dnds_uniques_withdoubles.png", width=1200)
par(mfrow=(c(1,2)))
boxplot(new$dnds~new$bias_ch, ylab="dn/ds", xlab="chromossome", main="New Genes' dn/ds", col=c("springgreen","rosybrown1","springgreen3","rosybrown3","springgreen4", "rosybrown4"))
boxplot(zan$dnds~zan$bias_ch,  ylab="dn/ds", xlab="bias", main="Genes' dn/ds", col=c("springgreen","rosybrown1","springgreen3","rosybrown3","springgreen4", "rosybrown4"))
dev.off()
png("dnds_uniques_withdoubles_besty.png", width=1200)
par(mfrow=(c(1,2)))
boxplot(new$dnds~new$bias_ch, ylim=c(0, 6), ylab="dn/ds", xlab="chromossome", main="New Genes' dn/ds", col=c("springgreen","rosybrown1","springgreen3","rosybrown3","springgreen4", "rosybrown4"))
boxplot(zan$dnds~zan$bias_ch,ylim=c(0,3.5),  ylab="dn/ds", xlab="bias", main="Genes' dn/ds", col=c("springgreen","rosybrown1","springgreen3","rosybrown3","springgreen4", "rosybrown4"))
dev.off()
png("dnds_uniques_withdoubles_samey.png", width=1200)
par(mfrow=(c(1,2)))
boxplot(new$dnds~new$bias_ch, ylim=c(0, 6), ylab="dn/ds", xlab="chromossome", main="New Genes' dn/ds", col=c("springgreen","rosybrown1","springgreen3","rosybrown3","springgreen4", "rosybrown4"))
boxplot(zan$dnds~zan$bias_ch,ylim=c(0,6),  ylab="dn/ds", xlab="bias", main="Genes' dn/ds", col=c("springgreen","rosybrown1","springgreen3","rosybrown3","springgreen4", "rosybrown4"))
dev.off()


# statistical tests to check different dn/ds in groups...
sink("dnds_withdoubles.txt")
cat("All genes (old and new):\n")
cat("Difference in dn/ds according to age group \n")
wilcox.test(zan$dnds~zan$age)
cat("Difference in dn/ds for X or A\n")
wilcox.test(zan$dnds~zan$XorA)
cat("Difference in dn/ds for X or A in Female biased genes\n")
wilcox.test(fem$dnds~fem$XorA)
cat("Difference in dn/ds for X or A in Unbiased genes\n")
wilcox.test(un$dnds~un$XorA)
cat("Difference in dn/ds for X or A in Male biased genes\n")
wilcox.test(mal$dnds~mal$XorA)

cat("\n\n\n")
cat("New genes:\n")
cat("Difference in dn/ds for X or A for new genes\n")
wilcox.test(new$dnds~new$XorA)
cat("Difference in dn/ds for X or A in new Female biased genes\n")
wilcox.test(newfem$dnds~newfem$XorA)
cat("Difference in dn/ds for X or A in new Unbiased genes\n")
wilcox.test(newun$dnds~newun$XorA)
cat("Difference in dn/ds for X or A in new Male biased genes\n")
wilcox.test(newmal$dnds~newmal$XorA)
dev.off()

#for all genes without doubles
zann<-read.table("nodoubles_tot.txt", header=T)
str(zann)
zann$bias_ch <- factor(zann$bias_ch, levels=c("A_male","X_male", "A_female","X_female", "A_unbiased", "X_unbiased"))
nnew <- subset(zann, age=="new")
nold <- subset(zann, age=="old")
nfem <- subset(zann, bias=="female")
nmal <- subset(zann, bias=="male")
nun <- subset(zann, bias=="unbiased")
nnewfem <- subset(nnew, bias=="female")
nnewmal <- subset(nnew, bias=="male")
nnewun <- subset(nnew, bias=="unbiased")

png("dnds_uniques_nodoubles.png", width=1200)
par(mfrow=(c(1,2)))
boxplot(nnew$dnds~nnew$bias_ch, ylab="dn/ds", xlab="chromossome", main="New Genes' dn/ds", col=c("springgreen","rosybrown1","springgreen3","rosybrown3","springgreen4", "rosybrown4"))
boxplot(zann$dnds~zann$bias_ch,  ylab="dn/ds", xlab="bias", main="Genes' dn/ds", col=c("springgreen","rosybrown1","springgreen3","rosybrown3","springgreen4", "rosybrown4"))
dev.off()
png("dnds_uniques_nodoubles_besty.png", width=1200)
par(mfrow=(c(1,2)))
boxplot(nnew$dnds~nnew$bias_ch, ylim=c(0, 6), ylab="dn/ds", xlab="chromossome", main="New Genes' dn/ds", col=c("springgreen","rosybrown1","springgreen3","rosybrown3","springgreen4", "rosybrown4"))
boxplot(zann$dnds~zann$bias_ch,ylim=c(0,3.5),  ylab="dn/ds", xlab="bias", main="Genes' dn/ds", col=c("springgreen","rosybrown1","springgreen3","rosybrown3","springgreen4", "rosybrown4"))
dev.off()
png("dnds_uniques_nodoubles_samey.png", width=1200)
par(mfrow=(c(1,2)))
boxplot(nnew$dnds~nnew$bias_ch, ylim=c(0, 6), ylab="dn/ds", xlab="chromossome", main="New Genes' dn/ds", col=c("springgreen","rosybrown1","springgreen3","rosybrown3","springgreen4", "rosybrown4"))
boxplot(zann$dnds~zann$bias_ch,ylim=c(0,6),  ylab="dn/ds", xlab="bias", main="Genes' dn/ds", col=c("springgreen","rosybrown1","springgreen3","rosybrown3","springgreen4", "rosybrown4"))
dev.off()


# statistical tests to check different dn/ds in groups...
sink("dnds_nodoubles.txt")
cat("Difference in dn/ds according to age group \n")
wilcox.test(zann$dnds~zann$age)
cat("Difference in dn/ds for X or A\n")
wilcox.test(zann$dnds~zann$XorA)
cat("Difference in dn/ds for X or A in Female biased genes\n")
wilcox.test(nfem$dnds~nfem$XorA)
cat("Difference in dn/ds for X or A in Unbiased genes\n")
wilcox.test(nun$dnds~nun$XorA)
cat("Difference in dn/ds for X or A in Male biased genes\n")
wilcox.test(nmal$dnds~nmal$XorA)

cat("\n\n\n")
cat("New genes:\n")
cat("Difference in dn/ds for X or A for new genes\n")
wilcox.test(nnew$dnds~nnew$XorA)
cat("Difference in dn/ds for X or A in new Female biased genes\n")
wilcox.test(nnewfem$dnds~nnewfem$XorA)
cat("Difference in dn/ds for X or A in new Unbiased genes\n")
wilcox.test(nnewun$dnds~nnewun$XorA)
cat("Difference in dn/ds for X or A in new Male biased genes\n")
wilcox.test(nnewmal$dnds~nnewmal$XorA)
dev.off()
